add missing ENABLE_MDNS in hyperiond.cpp (#1711)
build with out MDNS does not work:

```
hyperion.ng-git/src/hyperion.ng/src/hyperiond/hyperiond.cpp:298:9: error: ‘_mDNSProvider’ was not declared in this scope; did you mean ‘RRProvider’?
  298 |         _mDNSProvider->thread()->start();
```